name: meme_generator

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: Code Style with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle *.py
        pycodestyle ./quoteengine/*.py
        pycodestyle ./memegenerator/*.py
        
    - name: Doc Style with pydocstyle
      run: |
        pip install pydocstyle
        pydocstyle *.py
        pydocstyle ./quoteengine/*.py
        pydocstyle ./memegenerator/*.py
        
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint ./quoteengine/*.py
        pylint ./memegenerator/*.py
        #pylint app.py
        pylint meme.py
    - name: Tests with unittest
      run: |    
        python -m unittest
